account/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views
import django
from django.contrib.auth import views as django_auth_views # django内部认证
app_name = 'account'  # 增加app_name变量呼应 include中的namespace
urlpatterns = [
    # re_path('^login/$', views.user_login, name="user_login"),
    # path('login/', django_auth_views.LoginView.as_view(), name="user_login"), # 另一种写法如下
    path('login/', django_auth_views.LoginView.as_view(), {"template_name": "account/login.html"}, name="user_login"),
    # path('logout/', django_auth_views.LogoutView.as_view(), name="user_logout"),
    path('logout/', django_auth_views.LogoutView.as_view(), {"template_name": "account/logged_out.html"}, name="user_logout"),
    re_path('^register/$', views.register, name="user_register"),
    re_path('^password-change/$', django_auth_views.PasswordChangeView.as_view(), name='password_change'),
    re_path('^password-change-done/$', django_auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    re_path('^password-reset/$', django_auth_views.PasswordResetView.as_view(),
            {"template_name": "account/password_reset_form.html",
             "email_template_name": "account/password_reset_email.html",
             "subject_template_name": "account/password_reset_subject.txt",
             "post_reset_redirect": "/account/password-reset-done"},
            name='password_reset'),

    re_path('^password-reset-done/$', django_auth_views.PasswordResetDoneView.as_view(),
            {"template_name":"account/password_reset_done.html"},
            name='password_reset_done'),

    re_path('^password-reset-confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
            django_auth_views.PasswordResetConfirmView.as_view(),
            {"template_name": "account/password_reset_confirm.html",
             "post_reset_redirect": "/account/password-reset-complete"},
            name="password_reset_confirm"),

    re_path('^password-reset-complete/$', django_auth_views.PasswordResetCompleteView.as_view(),
            {"template_name": "account/password_reset_complete.html"},
            name="password_reset_complete"),

    re_path('^my-information/$', views.myself, name="my_infomation")
]

myblog/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path('^$', views.blog_title, name="blog_title"),
    re_path('(?P<article_id>\d+)/$', views.blog_article, name="blog_detail"),
    re_path('^accounts/', include('account.urls', namespace='account', )),
]

templates/base.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta http-equiv="X-UA-COMPATIBLE" CONTENT="IE=Edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="http://necolas.github.io/normalize.css/">
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>
<body>
    {% include 'header.html' %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    {% include "footer.html" %}
{#    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.js"></script>#}
{#    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>#}
    {% block javascript %}{% endblock %}
</body>
</html>

templates/footer.html
<div class="container">
    <hr>
    <p class="text-center">copy right <a href="http://127.0.0.1:8000/">苏俊峰</a></p>
</div>

templates/header.html
{% load staticfiles %}
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="http://www.dongao.com">
                <img src="{% static 'images/logo.jpg' %}" style="margin-inside: 3px;" width="60px" height="40px">
            </a>
        </div>
        <div>
            <ul class="nav navbar-nav" role="navigation">
                <li><a href="{% url 'blog_title' %}">My Blog</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li>
                    <div class="dropdown" style="margin-top: 8px">
                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu"
                                data-toggle="dropdown">{{ user.username }}
                                <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'account:password_change' %}">修改密码</a></li>
                        </ul>
                    </div>
{#                        <a href="#">{{ user.username }}</a></li>#}
                    <li><a href="{% url 'account:user_logout' %}">注销</a></li>
                {% else %}
                    <li><a href="{% url 'account:user_login' %}">登录</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
</div>
<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

templates/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block content %}
    <div class="row text-center vertical-middle-sm">
        <h3>登录</h3>
        <p>输入用户名和密码</p>
        <form class="from-horizontal" action="../templates/account" method="POST">
            {% csrf_token %}
{#            {{ form.as_p }}#}
            <div class="form-group">
                <label for="{{ form.username.id_for_label }}" class="col-md-5 control-label"
                       style="color: red"><span class="glyphicon glyphicon-user"></span>Username</label>
                <div class="col-md-6 text-left">{{ form.username }}</div>
            </div>
            <div class="form-group">
                <label for="{{ form.password.id_for_label }}" class="col-md-5 control-label" style="color:blue;">
                    <span class="glyphicon glyphicon-floppy-open"></span>Password</label>
                <div class="col-md-6 text-left">{{ form.password }}</div>
            </div>
            <div>
            <input type="submit" value="Login" class="btn btn-primary btn-lg">
            </div>
        </form>
    </div>
{% endblock %}